# Generated by Django 5.2.1 on 2025-06-01 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
    ]
